# Generated by Django 6.0.5 on 2026-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
