# Generated by Django 6.0.3 on 2026-05-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutsection_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='show_open_to_work',
            field=models.BooleanField(default=True, help_text='Show the Open to Work badge in the About section'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='show_open_to_work',
            field=models.BooleanField(default=True, help_text='Show the Open to Work badge in the Hero section'),
        ),
    ]
