# Generated by Django 6.0.3 on 2026-05-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_show_open_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='resume_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
