# Generated by Django 6.0.5 on 2026-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fix_resume_url_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='herosection',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
